/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    container: {
      center: false,
      padding: {
        DEFAULT: "1rem",
        sm: "1.25rem",
        lg: "1.5rem",
        xl: "2rem",
        "2xl": "2.5rem",
      },
      screens: {
        sm: "100%",
        md: "100%",
        lg: "100%",
        xl: "100%",
        "2xl": "100%",
      },
    },
    extend: {
      fontFamily: {
        sans: ["Inter", "Plus Jakarta Sans", "system-ui", "sans-serif"],
        display: ["Plus Jakarta Sans", "Inter", "system-ui", "sans-serif"],
        body: ["Inter", "Plus Jakarta Sans", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "IBM Plex Mono", "ui-monospace", "monospace"],
      },
      spacing: {
        0: "var(--space-0)",
        1: "var(--space-1)",
        2: "var(--space-2)",
        3: "var(--space-3)",
        4: "var(--space-4)",
        5: "var(--space-5)",
        6: "var(--space-6)",
        8: "var(--space-8)",
        10: "var(--space-10)",
        12: "var(--space-12)",
        16: "var(--space-16)",
        20: "var(--space-20)",
        24: "var(--space-24)",
        32: "var(--space-32)",
      },
      fontSize: {
        "display-xxl": [
          "var(--type-display-xxl)",
          { lineHeight: "1.08", letterSpacing: "-0.04em", fontWeight: "800" },
        ],
        "display-xl": [
          "var(--type-display-xl)",
          { lineHeight: "1.1", letterSpacing: "-0.035em", fontWeight: "800" },
        ],
        "display-lg": [
          "var(--type-display-lg)",
          { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "700" },
        ],
        display: [
          "clamp(2.75rem, 4.8vw, 4.75rem)",
          { lineHeight: "0.95", letterSpacing: "-0.03em", fontWeight: "700" },
        ],
        h1: [
          "var(--type-h1)",
          { lineHeight: "1.05", letterSpacing: "-0.03em", fontWeight: "700" },
        ],
        h2: [
          "var(--type-h2)",
          { lineHeight: "1.08", letterSpacing: "-0.03em", fontWeight: "700" },
        ],
        h3: [
          "var(--type-h3)",
          { lineHeight: "1.15", letterSpacing: "-0.025em", fontWeight: "600" },
        ],
        h4: [
          "var(--type-h4)",
          { lineHeight: "1.3", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        h5: [
          "var(--type-h5)",
          { lineHeight: "1.35", letterSpacing: "-0.015em", fontWeight: "600" },
        ],
        "section-display": [
          "clamp(2.75rem, 5vw, 5rem)",
          { lineHeight: "1.02", letterSpacing: "-0.03em", fontWeight: "700" },
        ],
        "body-lg": ["var(--type-body-lg)", { lineHeight: "1.75", fontWeight: "400" }],
        "body-xl": ["var(--type-body-xl)", { lineHeight: "1.75", fontWeight: "400" }],
        body: ["var(--type-body-md)", { lineHeight: "1.75", fontWeight: "400" }],
        "body-sm": ["var(--type-body-sm)", { lineHeight: "1.65", fontWeight: "400" }],
        caption: ["var(--type-caption)", { lineHeight: "1.5", fontWeight: "500" }],
        label: [
          "var(--type-label)",
          { lineHeight: "1.4", letterSpacing: "0.12em", fontWeight: "600" },
        ],
      },
      letterSpacing: {
        display: "-0.03em",
        heading: "-0.03em",
        "heading-sm": "-0.025em",
        section: "0.12em",
      },
      lineHeight: {
        display: "1.08",
        heading: "1.08",
        body: "1.75",
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        surface: "hsl(var(--surface))",
        "text-primary": "hsl(var(--text-primary))",
        "text-secondary": "hsl(var(--text-secondary))",
        "text-muted": "hsl(var(--text-muted))",
        "ds-success": "hsl(var(--ds-success))",
        "ds-warning": "hsl(var(--ds-warning))",
        "ds-error": "hsl(var(--ds-error))",
        "ds-info": "hsl(var(--ds-info))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: "hsl(var(--destructive))",
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        brand: {
          gold: "hsl(var(--brand-gold))",
          blue: "hsl(var(--brand-blue))",
          indigo: "hsl(var(--brand-indigo))",
          purple: "hsl(var(--brand-purple))",
          cyan: "hsl(var(--brand-cyan))",
          emerald: "hsl(var(--brand-emerald))",
        },
      },
      ringOffsetColor: {
        background: "hsl(var(--background))",
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        pill: "var(--radius-pill)",
      },
      boxShadow: {
        sm: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        DEFAULT: "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
        md: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
        0: "var(--shadow-0)",
        1: "var(--shadow-1)",
        2: "var(--shadow-2)",
        3: "var(--shadow-3)",
        4: "var(--shadow-4)",
        soft: "var(--soft-shadow)",
        premium: "var(--premium-shadow)",
        "glow-gold": "0 0 40px rgba(212, 175, 55, 0.25)",
        "glow-blue": "0 0 40px rgba(79, 140, 255, 0.25)",
        "glow-purple": "0 0 40px rgba(124, 92, 255, 0.25)",
        "glow-cyan": "0 0 40px rgba(0, 212, 255, 0.25)",
      },
      transitionDuration: {
        instant: "var(--duration-instant)",
        fast: "var(--duration-fast)",
        normal: "var(--duration-normal)",
        slow: "var(--duration-slow)",
      },
      transitionTimingFunction: {
        standard: "var(--ease-standard)",
        emphasized: "var(--ease-emphasized)",
        decelerate: "var(--ease-decelerate)",
      },
      maxWidth: {
        container: "var(--width-container)",
        section: "var(--width-section)",
        card: "var(--width-card)",
        panel: "var(--width-panel)",
        dialog: "var(--width-dialog)",
        drawer: "var(--width-drawer)",
        editor: "var(--width-editor)",
        dashboard: "var(--width-dashboard)",
        landing: "var(--width-landing)",
        "landing-wide": "112rem",
        "landing-prose": "52rem",
        reading: "var(--reading-width)",
        "reading-wide": "var(--reading-width-wide)",
      },
    },
  },
  plugins: [],
};
