import type { OverlayProps } from "../types/overlay";

export function AiHintOverlay({ question, ctx, isOpen, onClose }: OverlayProps) {
  if (!isOpen || !question) return null;
  const hints = question.hints ?? [];

  return (
    <div className="space-y-2">
      <div className="flex items-center justify-between">
        <h3 className="font-semibold text-sm">AI Hint</h3>
        <button type="button" className="text-xs underline" onClick={onClose}>
          Close
        </button>
      </div>
      {hints.length > 0 ? (
        <ul className="text-sm text-muted-foreground list-disc pl-4">
          {hints.map((h, i) => (
            <li key={i}>{h}</li>
          ))}
        </ul>
      ) : (
        <p className="text-sm text-muted-foreground">
          Hints will appear here when generated by AI tutor.
        </p>
      )}
      <button
        type="button"
        className="text-xs text-primary underline"
        onClick={() => ctx.ai?.requestHint?.(question.questionVersionId)}
      >
        Request hint
      </button>
    </div>
  );
}
