FROM node:20-alpine

# Use an official docker client so the worker container can spawn ephemeral child containers through the mounted socket.
RUN apk add --update docker openrc
RUN rc-update add docker boot

WORKDIR /app
COPY package*.json ./
RUN npm ci

COPY . .
RUN npx tsc -b

CMD ["node", "dist/queues/worker.js"]
